apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/instance: conprof
    app.kubernetes.io/name: conprof
    app.kubernetes.io/version: 87e6b61b1feb
  name: conprof-objectstorage
  namespace: conprof
stringData:
  conprof.yaml: |-
    "config":
      "directory": "/tmp"
    "type": "FILESYSTEM"
