apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/instance: conprof
    app.kubernetes.io/name: conprof
    app.kubernetes.io/version: 87e6b61b1feb
  name: conprof
  namespace: conprof
spec:
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app.kubernetes.io/instance: conprof
      app.kubernetes.io/name: conprof
  serviceName: conprof
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: conprof
        app.kubernetes.io/name: conprof
        app.kubernetes.io/version: 87e6b61b1feb
    spec:
      containers:
      - args:
        - all
        - --log.level=debug
        - --storage.tsdb.path=/conprof
        - --config.file=/etc/conprof/conprof.yaml
        - --objstore.config=$(OBJSTORE_CONFIG)
        env:
        - name: OBJSTORE_CONFIG
          valueFrom:
            secretKeyRef:
              key: conprof.yaml
              name: conprof-objectstorage
        image: quay.io/brancz/conprof:08a162ee22cd
        name: conprof
        ports:
        - containerPort: 10902
          name: http
        - containerPort: 10901
          name: grpc
        volumeMounts:
        - mountPath: /tmp
          name: tmp
          readOnly: false
        - mountPath: /conprof
          name: storage
          readOnly: false
        - mountPath: /etc/conprof
          name: config
          readOnly: false
      nodeSelector:
        kubernetes.io/os: linux
      serviceAccountName: conprof
      volumes:
      - emptyDir: {}
        name: tmp
      - emptyDir: {}
        name: storage
      - name: config
        secret:
          secretName: conprof
