apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: symbolicator
    app.kubernetes.io/name: symbolicator
  name: symbolicator
  namespace: conprof
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: symbolicator
      app.kubernetes.io/name: symbolicator
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: symbolicator
        app.kubernetes.io/name: symbolicator
    spec:
      containers:
      - args:
        - run
        - --config=/etc/symbolicator/config.yaml
        image: quay.io/conprof/symbolicator:v0.3.3
        name: symbolicator
        ports:
        - containerPort: 3021
        volumeMounts:
        - mountPath: /etc/symbolicator
          name: config
          readOnly: true
        - mountPath: /tmp/symbolicator
          name: cache
          readOnly: false
      serviceAccountName: symbolicator
      volumes:
      - name: config
        secret:
          secretName: symbolicator
      - emptyDir: {}
        name: cache
